### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#107]

**Comment by jessica-azgs** [comment]
Need to get data out of strabo app to use somehow

**Comment by jessica-azgs** [comment]
Working for Android and web browser use. Saves a .csv file for Android and writes to a new browser window for the browser. @ginxwar Could you look at this for iOS? Should just be adding a conditional statement and changing where the file is stored for iOS. Guess if it's not iOS or Android or web browser (eg. Windows phone, though I doubt anyone is using that - PhoneGap Build is just making it for us automatically) it can just do the web browser action. You can merge in the branch after testing.
http://ngcordova.com/docs/plugins/file/
https://github.com/StraboSpot/strabo-mobile/tree/CSVexport

**Comment by ginxwar** [comment]
I took a look at this.  It does appear that all you need to change is the cordova file location specific for iOS devices.  So I ended up trying them all:
```
cordova.file.dataDirectory
cordova.file.cacheDirectory
cordova.file.tempDirectory
cordova.file.syncedDataDirectory
cordova.file.documentsDirectory
```

But for every one of them, I kept getting a FileError code 5, which is an ```ENCODING_ERR``` error.  It looks like the solution is to maybe use ```window.resolveLocalFileSystemURL``` for these file locations and then writing to those locations *after* you resolve them, but I haven't tested this theory yet.  Googling this subject is somewhat limited.

I'll try again tomorrow.

**Comment by ginxwar** [comment]
Fixed in 6dc06ba9a66090a2074de51f1bb4670b76a60cb7

**Comment by jessica-azgs** [comment]
On Android the strabo folder with the csv file is just in my root directory. I can find that easily with the file manager that came on my S6 though it's easy enough to download a file manager program as well.

For iOS I downloaded FileMaster but I can't find the actual file to open the csv. @ginxwar Do you know how to see it on the device, not with XCode?

**Comment by zmichels** [comment]
Yeah... How do I get to this exported file on iOS device? Usually for apps with exportable info, I can access the files through iTunes. I don't see it there. Do I need a different program? Can we instead make it available through iTunes? I'm guessing most people using iOS devices will be familiar with this process if we could get it working.

**Comment by ginxwar** [comment]
Ugh.  So it looks like cordova-plugin-file's documentation for iOS for file system shows that every location is **private**.  This is unlike Android where ```cordova.file.externalRootDirectory``` is **public**.  I'm guessing this is due to Apple's sandbox security model where each app can only access documents specific to that app's UUID.  This also explains why when we use a 3rd party file manager like FileMaster on iOS, it really doesn't show anything other than its own accessible files.  FileMaster is also a bit unique in that it shows up in iTunes as a "File Sharing" app.  But there's no ability in Cordova that I've researched that can transform an app into a "File Sharing" app.

The other thing I tried was to save the file in an iCloud enabled directory but I still can't see it in my iCloud account.  I'm not sure if you need to wait for some time period before iCloud sync'ing kicks in, which makes this a bit more difficult to debug/test.

@zmichels in your experience, how have you seen file access in iTunes?  In iTunes, do you navigate to the apps pane and click on the app to see its internal files?  How do you transfer back and forth between your iPad and your computer that's not a movie, video, tv show, etc.?

I've posted a StackOverflow question about this.  Maybe I'll get lucky.

**Comment by zmichels** [comment]
For iTunes file sharing apps...
I typically plug on the device, click on it in iTunes and navigate to the Apps portion.
If I scroll down past the list of installed apps in the main screen, then there is another list of installed apps that have some file sharing/syncing options... And any data on the device can be accessed.
Typically drag and drop into or from iTunes.

**Comment by ginxwar** [comment]
@zmichels That sounds like it's an app that has "File Sharing" enabled which is unique to iOS.

**Comment by zmichels** [comment]
That may very well be, but that is how I have mainly experienced file access in iTunes.

**Comment by ginxwar** [comment]
@zmichels you gave me a clue in solving this issue.  Fixed in 948eb45c542132bb6eca1e4f83ddb22721e7a1cb.

The strabo-mobile app now shows up in iTunes, under File Sharing.  You should see two folders:

* NoCloud
* strabo

Not sure if we care about iCloud syncing, but currently it is set to sync to your iCloud account.  May be easier to use instead of iTunes.  (But this is untested)

**Comment by zmichels** [comment]
@ginxwar That is great news. But, I just rebuilt the app on phonegap and updated my device... And I don't see StraboMobile in the file sharing apps under iTunes. What am I doing wrong?

**Comment by ginxwar** [comment]
Can you share the phonegap build page where you download the latest version
of the app?  I think it needs to be rebuilt.

-Kevin

**Comment by jessica-azgs** [comment]
@zmichels Did you update the code or just rebuild on phonegap build? I just updated the code now. Can you try again?

**Comment by zmichels** [comment]
Just rebuild. About to leave service, I will try right now.

**Comment by zmichels** [comment]
App is now listed in iTunes file sharing, but exported data are not showing up.

**Comment by zmichels** [comment]
Deleted app on device for which file sharing wasn't working and did a clean install. Lost data, but now the export seems to work. Question. Is this CSV format something that StraboSpot can read in? Are the ties to photos lost?

**Comment by ginxwar** [comment]
Currently, no.  If that's a feature, we should create a new issue.  Right now, the data on the device is stored a bit differently (JSON) so there is conversion that happens going from JSON to CSV.

If we want to import a CSV to devices, we would need a CSV to JSON converter, and that conversion has to be of a certain schema.
