### ISSUE TITLE
Make photos viewable in app

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#108]

**Comment by jessica-azgs** [comment]
Picture is so small. Click on picture and it opens bigger. Add ability to save picture to device.

**Comment by ginxwar** [comment]
See 6f89be1d49d8a37f20a5ec05cda18ae356820c8e.  I added:

* an active-slider to the images so that you can better view images
* auto save the image to the /Pictures folder in Android

There may be some performance/lag during the load and scroll of multiple images because the testing I ran on my Nexus4 show a pretty large images.  But this commit fully addresses the issue for my Android device.

Of course, this doesn't work in iOS yet :( so I'll still need to refactor this for iOS.  The error is:

"Can't find variable: LocalFileSystem"

**Comment by jessica-azgs** [comment]
Yeah, I got some lag too on the scroll on my Samsung S5 with Android 5.0. Also crashed when I tried to add a picture from camera, not from file. Crashed out of the form and back to the map w/o adding the picture.

Also, I don't know how this plays into the active-slider but the team mentioned wanting to be able to caption/write notes for each picture.

**Comment by ginxwar** [comment]
Finally got this to work in commit 5471a51a6177620cf381cedd5f4caeb8f1cce354.  On my iPad mini, it's pretty speedy, but on my Nexus 4, it's a bit slow.

Caveats:

* to speed up image processing, we may want to store thumbnails alongside the original image
* iPad image saving goes directly to the Photos app, which is great, but on Android 5.0.1, it goes into ```/sdcard/Pictures/```  The problem is that the Photos app in Android is sync'ed up with Google+ and they try to make it all fancy by leveraging Picasa albums.  So if you go into your Photos app, you can't see your images, because you're really looking at ```/sdcard/Picture/cache/com.google.android.g/picasa*```  I can verify the images by [ES File Explorer Manager](https://play.google.com/store/apps/details?id=com.estrongs.android.pop&hl=en)

We may need to revisit this again.

**Comment by ginxwar** [comment]
Linking https://github.com/StraboSpot/strabo-mobile/issues/100

**Comment by ginxwar** [comment]
Referencing https://github.com/StraboSpot/strabo-mobile/issues/100

**Comment by ginxwar** [comment]
From Jessica:

"Oh, regarding viewing pictures, can you make them full screen instead of floating on top, and with a caption at the bottom, like Facebook does their pictures? I think that will look better."

**Comment by ginxwar** [comment]
Files in android dropped in /Pictures eventually get displayed in the Photos app. Confirmed on my Nexus device this morning   I wonder if google+ auto backup checks on a schedule and builds the necessary cache for this to be displayed in the app

**Comment by ginxwar** [comment]
Commit 93acf5ace0723eaf203c7d46eda28ef63c1b2b30 now has ability to add captions

**Comment by ginxwar** [comment]
The caveat regarding performance remain -- we may need to store thumbnails alongside the original image or downgrade the original captured image altogether.  See comments above.

**Comment by smrazgs** [comment]
@ginxwar It looks like this should be closed. If there are other issues around using photos, create new issues.
