### ISSUE TITLE
Spots as a single map layer

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#11]
Spots should be able to viewed or hidden as a layer in the map view.

**Comment by ginxwar** [comment]
Can you clarify if all the spots should belong into a single layer?  And if so, what would multiple layers look like?  If there is a maximum of 100 spots per layer, would additional spots beyond 100 be shown in a different layer?

Currently, each layer can be toggled for view on or off.

**Comment by zmichels** [comment]
Hmm. 
I may be misunderstanding the question...
I think ideally, users could choose from available spots (as different layers?). Since a spot can be pretty much anything, maybe users would prefer layers of similar spot types from which to display (does that make sense?). Something like a layer of all the foliation measurements (or maybe all planar features), or lineations, or contacts/faults... Etc.
As for a 100-spot maximum, if there are more than 100 spots requested to show, I *think* it makes sense to serve them up in more than one layer.
