### ISSUE TITLE
Zoom to extent of spots

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#112]
Have a button to zoom to the map extent of all the spots that are currently loaded

**Comment by ginxwar** [comment]
See 6217b842593c64e599a3255911595f8d53b78c48.  The logic for first map load is:

*  if it has a mapView, load that extent first (this is due to map reuse through spot editing menus)
*  otherwise, if we have ANY spots at all, build an extent and load that extent
*  finally, if neither of the two above, build the extent from the geolocated position
* if geolocate fails, alert the user of a problem

**Comment by ginxwar** [comment]
It looks like we could do animations in OL3 via examples shown in http://openlayers.org/en/v3.4.0/examples/animation.html.  This would be neat to implement and could be useful to visually show folks that we're zooming to the extent of the map.

**Comment by ginxwar** [comment]
See b5ecb44e54f08d2ff599adaf2ecc08e2359da638.  I added a fly-by animation for spot extent.  The user now has a better idea of where the spots are initially loaded.

**Comment by jessica-azgs** [comment]
The fly-by looks slick. @ginxwar Can you make it so
(1) it doesn't zoom in so far if there is only 1 spot?
(2) when the new button on the map header to zoom to the extent of the spots is pressed, can the fly-by start from the current location?

**Comment by ginxwar** [comment]
Both done in commit 8a5b2fc94de077197ee6d15c36dc09c3aa5af7bd, cd36858f88b90879df7888d3fe2c59fa9ed9166b
