### ISSUE TITLE
sync page

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#132]
This button on the main app page should be relabeled. This button does more than just sync with the databse. The option on the sync page allows control of the project and logout function. Maybe "database options" or simply "Settings"?

On the sync page the logout, download, upload and delete buttons are unnecessarily large as is the screen space between them. On my phone the download and upload progress is located out of the screen area.

The upload and download function seems to work now

**Comment by JEAndrew** [comment]
Correction: the app sync funtions have deleted my database shapefile uploads again this morning.

**Comment by jessica-azgs** [comment]
@JEAndrew I moved the login/logout to the Settings page and all database operations are now done from the Spots page by clicking the loop icon at the top of the page. I'm closing this issue since there is no more sync page and any new issues/comments you find with the upload/download/dataset functionality can be put in new issues.
