### ISSUE TITLE
Adding pictures on Android crashing app

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#157]
Recently adding pictures on Android, either via camera or the gallery, is crashing strabo. Doesn't happen every time, but most of the time. This was working before. I haven't encountered this problem on iPad. Maybe this has to do with Google's recent Photos update?

**Comment by ginxwar** [comment]
I can confirm that this bug still exists in Android.  iOS works fine.

The issue is at some point during our upgrade process (cordova, plugins, google photos, android system, etc) something changed the URI location of the Photo Albums image.  Previously, the URI schema was something like:

    file://some/path/to/the/image

But now the URI schema is:

    content://some/path/to/the/image

Because of this, ```window.resolveLocalFileSystemURL``` (https://github.com/StraboSpot/strabo-mobile/blob/master/www/js/controllers/tabs/SpotTabPhotos.js#L148) no longer can resolve this URI schema.

See my comment here: http://stackoverflow.com/questions/30640251/cordova-resolvelocalfilesystemurl-error-code-1000-in-android in response to a contributor who claims to have fixed this.

The JIRA issue seems to indicate this is an open bug: https://issues.apache.org/jira/browse/CB-7024

I'd like to revisit this issue in a few days to see how these issues get responded.

**Comment by jessica-azgs** [comment]
@ginxwar Can you test this out on your devices with ngCordova v0.1.17-alpha? I was able to add pictures without the app crashing on my S6 with this version of cordova. We're still using v0.1.11-alpha in the app. See if it works for you as well and if it does, how upgrading may affect anything else.

**Comment by ginxwar** [comment]
Fixed in b1a0637988b4f03cdef55c4971e3ad6b2f73071c.  I tested both the Camera and the Photo Library functionalities on both my Nexus4 and iPad.  I did not use ngCordova v0.1.17-alpha.

I came across a [cordova-plugin-filepath](https://github.com/hiddentao/cordova-plugin-filepath) plugin that addresses the the ```content://``` schema issue while the [main JIRA bug](https://issues.apache.org/jira/browse/CB-7024) sits open on the Apache site.

The main problem is that ```window.resolveLocalFileSystemURL``` cannot resolve the URI if the schema is in the ```content://``` schema.

**Comment by zmichels** [comment]
Kevin,

Hope you are doing well!
Do you want me to add your iPad UDID to the license? I don't think ice added yours. Let me know before tonight and I can try to add it before heading to the field for the next month.

Cheers,
Z

**Comment by ginxwar** [comment]
@zmichels Thanks for the offer, but I've got my own Apple Developer Program account and that's how I've been debugging Strabo on my iPad.  It took a bit to figure out and setup, but once it's done, it's not too bad.

Have fun out in the field!

**Comment by jessica-azgs** [comment]
cordova-plugin-filepath is not supported in phonegap build though (https://build.phonegap.com/plugins) which is what we're using to build and distribute the app. If upgrading to ngCordova v0.1.17-alpha does fix the problem, and doesn't break anything else, it seems like that would be the better solution than applying a "patch" for an outdated version of ngCordova anyway. The main JIRA bug is pretty old.

**Comment by ginxwar** [comment]
cordova-plugin-filepath is now listed in the phonegap build in 23826c14fe01e25acd80e1e8317a12fba3ed3222.  This issue should be fixed now.

**Comment by JEAndrew** [comment]
adding photos worked today on my samsung galaxy 5

**Comment by panamint55** [comment]
Are you back in town?

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by zmichels** [comment]
I'm now in Boise tonight. On the way to Seiad field area in California. Hope to get settled there by 17th. Plan to stay with a friend near Seiad tomorrow night. I'll be in and out of the area until ~August 13th.

Cheers,
Z

**Comment by jessica-azgs** [comment]
Seems to be working now.
