### ISSUE TITLE
Upgrade to cordova 5.1.1 in PhoneGap Build

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#159]
Didn't work when tried to upgrade (commit 971c74805db8e10a62c6135576a823b244b7da7b). Need to revisit this.

**Comment by jessica-azgs** [comment]
Tried a bunch of different changes to config.xml again and still can't get it to build in PhoneGap Build with cordova 5.1.1. This is not ideal since 5.1.1 is what we're both using and testing locally. @ginxwar Do you want to see if you can have any better luck?

**Comment by ginxwar** [comment]
Fixed in 23826c14fe01e25acd80e1e8317a12fba3ed3222.  Phonegap build now says
![image](https://cloud.githubusercontent.com/assets/1930629/8691866/16ba5e1a-2a7d-11e5-9b07-3e99f14d027f.png)

Plugins are now correctly stating versions too:
![image](https://cloud.githubusercontent.com/assets/1930629/8691878/3007e856-2a7d-11e5-96d6-ffd95b4b9960.png)

**Comment by jessica-azgs** [comment]
Great! Added the whitelist plugin with commit 88f44c630b71a808144a02aa89ead9b6d7f6e228 since this is needed to control which network requests (images, XHRs, etc) are allowed to be made.Policy just using defaults right now so still need to set that up.
