### ISSUE TITLE
How do I get the spot name to be a name from my shapefile?

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#163]
I am trying to upload some sample location data, and I have a field for the sample name. To what do I assign this attribute when uploading so that when I download to StraboMobile it will list the text I want for the name of spots in the spot list (stations and groups)?
Right now, it seems that no matter what I select, the "name" in the spot list (stations and groups)is a long number. I need this to be sensible so that I can look at the list and know what the data are.

**Comment by zmichels** [comment]
Also, when I add Groups in the app, I want the list of groups to show the group name I entered rather than a long number. How can I do this?

**Comment by jessica-azgs** [comment]
@jasonash Whatever the user wants to use as the name needs to be mapped to the name field. (spot.properties.name) Relatedly, whatever the user wants as the label needs to be mapped to label (spot.properties.label). Is this how you are doing it server-side?

@zmichels The name for the group is set on the Notes page - the same as it is for every other type of spot. This is the field that needs to be filled in, otherwise it will default to a long number. You can set your own default for the name field from the settings page.

**Comment by jasonash** [comment]
@jessica-azgs OK, spot.properties.name already existed, but I just added spot.properties.label.
@zmichels When you upload your shapefile, there will be a "Name" and "Label" option for your columns at the very bottom of the select-list. These should control behavior on the app-side. Hope this helps.

**Comment by zmichels** [comment]
Still not working. I assigned the string I want to Name field during shapefile upload... Still imports to app as a string of numbers (for Spot Name). I updated to latest version and tried, but still numbers.

**Comment by jasonash** [comment]
@zmichels I'll do some experimenting to try and figure out what is going on. Sorry for the trouble.

**Comment by jasonash** [comment]
@zmichels I just uploaded a shapefile and used the "Name" field and the strabo app correctly displays the name on the map. (See Attached) 
![screenshot_2015-07-21-16-08-13](https://cloud.githubusercontent.com/assets/7904402/8813409/eb52ef5c-2fc8-11e5-9117-c2a671b51819.png)
Can you try your upload again?

**Comment by zmichels** [comment]
Thank you. Name field is now working. Have not tried the labels, but looks like worked for you.
