### ISSUE TITLE
Downloaded Map Tiles not showing on any devices

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#165]
After downloading map tiles for offline use on iPhone, iPad, and Android tablet... None of them show when offline. On Android, get fuzzy green map color background. On iOS devices get tiles that say "Offline Tile Unavailable. This is going to make it hard to use in the field for the next week. This needs to get fixed ASAP. But I am going to have to deal with it in the field until I can get back to reception or find any on a mountain to hear back.

**Comment by ginxwar** [comment]
@zmichels when we upgraded to OL3 v3.6, the entire offline maps functionality broke.  OL3 v3.7 fixes what OL3 broke in v3.6.

Fixed in bf29d4aa048aaa2219429e86416908a65073f7c9, 74f15ac8a64a4a7451f1a04ff14e72f4c1380fb8, but I'll let @jessica-azgs review this before she makes the next build available to you.

**Comment by jessica-azgs** [comment]
@zmichels @ginxwar This is working for me now on both android and ios and pulled inot phonegap build.
