### ISSUE TITLE
spots annotate on photos

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#192]
When I add a point spot (same result when add other types of spots) in annotate photo, the app then goes back to the upper level spot tab and rewrites new lat long in pixel space coordinates (e.g.; 1388, 1222). These number exceed lat-long possibilities (90 & 180) so there is a validation error.

Am I doing something wrong?

I am using an up to date Samsung Galaxy 5.

**Comment by jessica-azgs** [comment]
In my workflow I create a spot (say 'Awesome Outcrop'), add an image to that spot, give it a caption (say 'Red Rock') and click the annotate button. I then go to the Image Basemaps menu item and open the 'Red Rock' image. Now if I add a point on the 'Red Rock' image Strabo immediately opens a page for the new spot that is nested within the 'Red Rock' image. This Spot (say 'Spot in Red Rock') does have pixel coordinates since it is mapped on the image. If I leave 'Spot in Red Rock' and go back to the original spot 'Awesome Outcrop' it still has its original geographic lat/long coordinates. Using my workflow everything seems to be working fine.

This works the same for me on my S6 and through the web interface. How is your workflow different @JEAndrew? I want to recreate your error.

**Comment by panamint55** [comment]
Are you around for a call in 30 minutes or so?

Doug

***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by JEAndrew** [comment]
I can, I am doing a home visit right now, Naia was going crazy and Steph needed backup.



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by jessica-azgs** [comment]
I think I found what you were talking about. It was a much different workflow than I was using but see if you still get that problem with version 0.9.1 @JEAndrew. Thanks!

**Comment by JEAndrew** [comment]
Ok, I'll try it out and let you know...
