### ISSUE TITLE
annotate image problems

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#194]
It is difficult to check the annotate button because the folded map symbol pops up and covers it. Maybe we should default to having name because otherwise it shows up as "untitled 0" in the image map list

**Comment by jessica-azgs** [comment]
@JEAndrew Been working on this over the past few days as I redo the Images tab but I haven't pushed  up the change to PhoneGap Build since I'm not quite finished. Also, in the new Images tab if you want to use an image as an image basemap you are required to give it a Name first. This is different from the image description field.

**Comment by jessica-azgs** [comment]
fixed with commit e00e91c962a172468311a4afd6b4cfe77a7d4a87
