### ISSUE TITLE
Bad data entry causes app-trastrophe

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#209]
How did you and Doug solve his erroneous data problem in strabo app in January? 

I have made bad data entries twice today, where I start a feature and then realize it is a mistake and without thinking hit the Android hardware 'back' key. This causes a crash and then strabo will not stay open long enough to even log in. Last time, I unistalled/reinstalled but lost all of the data. This time I have been uploading often (a not very efficient method) so I won't lose data.

**Comment by jessica-azgs** [comment]
We just deleted all the Spots from the Spots page since we didn't know which one was messing up the app.

What are your exact steps to cause the crash? What page are are you starting a feature from? Does it happen with a fresh install of the app with new Spots (not downloaded Spots)?

Unfortunately loss of data is inevitable as the app/server is still in development. Every feature change would take twice as long if we had to 'save' all previous data.

**Comment by JEAndrew** [comment]
I think the problem was caused by me hitting the hardware return/back key on the Samsung tablet while I was in the middle of drawing a line. I will try experimenting to recreate it.

**Comment by jessica-azgs** [comment]
I just tried that and the app crashed for me too. Good job finding that bug!

**Comment by JEAndrew** [comment]
I still have problems. I can Uninstaller then reinstall, then download and strabo will work for a while. Last time the data had their unit labels all erased. After a while strabo will then crash and I am back to un/reinstall. Otherwise app doesn't even login, just crash

**Comment by JEAndrew** [comment]
WIth help from Jason we were able to find two bad spots I had created using the back/return samsung hardware button. These spots both were missing 'geometry'. After these were deleted the app works again
