### ISSUE TITLE
Copy spot puts the new one exactly on top of the original

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#295]
Copy spot puts the new one exactly on top of the original.  In the past, when the new spot came up there was an option to "set on map."  Now that is gone.  The only way to select the spot is to use the edit mode to move it.  This moves both spots.  

I think adding the set from map back to the copied spot is a good idea.  That way you can copy to get all the attributes and tags, but then put it in a new location.

**Comment by jessicagood** [comment]
I changed it so the geometry is not copied. Then, since there is no defined geometry for the spot, you get the "Set on Map" option.

Another note about your comment: Since tags are not stored in the spot (they are stored in the project) they are not copied when a spot is copied. Do you need the tags copied as well?

**Comment by panamint55** [comment]
If you copy a spot the tag should also be copied.  Maybe an option on to copy?  That seems pretty complicated.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessicagood** [comment]
Fixed with commit 4856680a723baa4d2a65dbbe82a57ed696c377f2.
I just set it up to copy the tags by default. An option to copy tags or not copy tags is more complicated for the user.
