### ISSUE TITLE
Expand Options for Database Endpoint

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#314]
Right now, we have the option to specify a Database Endpoint URL which defaults to http://www.strabospot.org

Could we expand this capability to specify a complete path to the API, including port?

For example, I would like to be able to specify:

http://www.strabospot.org/devdb:8081

This would greatly increase our ability to debug.

Also, there should probably be a button on this page that a user could click to put the "default" value back into the field in case it is changed inadvertently.

**Comment by panamint55** [comment]
Sounds good.  Or keep a record of URLs that have been used and have those as options.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessicagood** [comment]
@jasonash I changed the default db endpoint url from `http://www.strabospot.org` to `http://www.strabospot.org/db`. This is effective in the latest version on PhoneGap Build though I didn't update the version number yet. This gives you more flexibility when you change it on the Miscellaneous page. You can include a port too if you wish. 

Since the authenticate user API call doesn't follow the same URL structure as the rest, the app removes the last '/' and anything after it when making that call. This works but if you prefer to have it consistent and change the API let me know and I can easily change this one.

There is already a reset URI button on the right side, on the same line that says Specify Database Endpoint.

**Comment by jasonash** [comment]
@jessicagood I'm wondering if it might make sense to move the authenticate controller into the db/ folder. This would slightly change the behavior of the API. On success, it would still return:

`{
  "valid": "true",
  "profileimage": "http://strabospot.org/db/profileimage"
}`

but on failure it would return a 401 (unauthorized) header and no content. Would this be feasible? Can your code look for a 200 vs 401 instead of the response body?

**Comment by jessicagood** [comment]
Yeah, sure, it's easy to change the code for the app if you want to do that.

**Comment by jasonash** [comment]
OK, I've moved the authentication controller into db/.

The endopoint is now:

http://strabospot.org/db/userAuthenticate

Basically, you do a POST with an empty body and basic authentication (like the rest of the API functions) and it returns a standard success message if valid:

`{
  "valid": "true",
  "profileimage": "http://strabospot.org/db/profileimage"
}`

and gives a 401 (unauthorized) if the credentials aren't good.

I hope this makes sense. Let me know if you have any questions.

I left the original authentication controller in place for legacy builds. We can remove this down the road if we want.

**Comment by jessicagood** [comment]
Ok. I implement that. It'll be in the next version. That cleans up the authentication a bit.
