### ISSUE TITLE
Android App Crashing

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#316]
Using Strabo Mobile version 0.15.4 (downloaded 11-02-2016)

After installing Strabo Mobile on my Android device, I logged into the test account at strabospot.org and downloaded the Malpais dataset. This worked without error, and all spots and pictures were downloaded fine. After quitting the application though, and then re-opening, the app immediately reports "Unfortunately Strabo Mobile has stopped" and the app crashes. The only way to recover from this error is to uninstall and reinstall the application.

I reproduced this on four Android devices:
Samsung Galaxy S7
Google Nexus 7 2013
Motorola MotoX 2013
Motorola MotoX 2015

**Comment by egbunse** [comment]
This is almost exactly what happened to me at Malpais Mesa when I tried using the app on my Galaxy S5 (and is why I used iPads the rest of the time there). I put my observations in Issue #193

**Comment by jasonash** [comment]
I tried the exact same routine above on an iPad this morning and the application is working fine. No crashes, and able to reboot without problem. This particular issue seems confined to Android devices.

**Comment by jessicagood** [comment]
Yeah, we were having this issue last week too, I just haven't been able to
fix it yet since we've been having so many other problems recently too. It
seems like it's only happening with this project. I can read in thousands
of Spots from one of Joe's projects in Android, close the app and it opens
again fine.

I think it's crashing as it is reading in the spots from the local
database. Since the images have been stored in the spots and this project
has almost 200 images the app/local database can't handle the amount of
data. The iOS database is stored slightly different. Next week I want to
separate out the images into their own database and not read from that
database until a user actually wants to look at an image. That seems to
make more sense in any case, it just hadn't been an issue yet so I hadn't
changed it.

You could test this, if you wanted, by removing all the images in Malpais
Mesa in the test account and downloading. But I can do that next week too.
Hopefully that will solve it. If not there must be something else wonky
with this dataset.

On Nov 2, 2016 8:39 AM, "Jason Ash" <notifications@github.com> wrote:

I tried the exact same routine above on an iPad this morning and the
application is working fine. No crashes, and able to reboot without
problem. This particular issue seems confined to Android devices.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/StraboSpot/strabo-mobile/issues/316#issuecomment-257903321>,
or mute the thread

**Comment by jessicagood** [comment]
@egbunse and @jasonash Can you confirm this is working OK now on your devices? Thanks!
