### ISSUE TITLE
Remove decimal points from dip and strike in orientations

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#354]
Right now all orientation data are reported to two decimals.  These need to be rounded to single degrees for display, and to one decimal point for the database.  Display means in the orientation tab and its result.

**Comment by jessicagood** [comment]
I remembered this [issue 274](https://github.com/StraboSpot/strabo-mobile/issues/274) which hasn't been addressed yet. Someone else (I think @btikoff) said strikes should be three digits (eg. 003) and dips 2 digits. No decimals.

I can do either style (though your style is easier @panamint55) but it would be more difficult to display one number (no decimals) and store another (one decimal place) as the input field in the Orientation tab is the same as the display. I can display a rounded value on the map though since the value is not inputted there.

**Comment by jessicagood** [comment]
For either solution I have to allow the user to enter in whatever they want as long as it's a valid number which follows the validation criteria set in KoBo forms (eg. strike must be 0-360). And then after they save the orientation data for the plane or whatever they're entering I can strip down the number to the format you want. This may not go over so well if someone does actually want to save decimals and then sees them disappear after they save the orientation. But maybe there is no use case for that. I just wanted to point it out.

**Comment by jessicagood** [comment]
*This is also a comment for duplicate issue https://github.com/StraboSpot/strabo-mobile/issues/358.  Fixed with commit 23e0d6d. (But not released yet.)*

@panamint55 @rtwilliamsgeo The user will be told that an entry is invalid for an integer field if an integer hasn't been entered. If you want to restrict the input to whole numbers you will need to set that up within the validation criteria for each applicable field in KoBo forms. A lot of them have been set up already. See the list in the next comment below for all fields that have been specified in KoBo forms as integers. You can also easily see which have validation criteria and which do not.

If any fields are incorrectly set as integers you may want to switch them to decimal fields in KoBo forms before the next release and let me know when you've made the updates so I can pull them into the app. Likewise if you'd like give some validation criteria to fields that are lacking it.

The compass had also been outputting strikes, etc with 2 decimal places. Since you only want whole numbers in the fields now I've adjusted this as well.

Note that all of this will only apply to new data inputted or if a user edits saved data. @jasonash may be able to strip all the decimals out of specified fields in the database if that's something you want.

**Comment by jessicagood** [comment]
Integer fields:

![image](https://cloud.githubusercontent.com/assets/1493985/23966062/438744f0-0977-11e7-9026-322c195416ce.png)
![image](https://cloud.githubusercontent.com/assets/1493985/23966110/6c8bf80a-0977-11e7-9ac6-913bdb41fae2.png)
