### ISSUE TITLE
Symbology Missing

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#355]
From @zmichels: Lineations are not plotting as arrows. Showing up as dots. We will want these to plot as arrows that point in the direction of the trend/azimuth. In the attached images, I am showing a single spot with a foliation and a lineation. I tried entering them two different ways... as separate features/orientations, and as associated features ( with the Lineation added to the foliation). The foliation symbol plots very nicely, but neither case leads to a lineation symbol. When they are separate features, the lineation shows up as a dot/point. When they are "associated", only the foliation symbol plots, and there is no indication of an associated lineation. Ideally, the lineation arrow would be plotted in addition to the foliation symbol.

![img_6953](https://cloud.githubusercontent.com/assets/8769619/23310987/16d79eca-fa7a-11e6-9d76-1b5d2f9dedd3.PNG)

![img_6952](https://cloud.githubusercontent.com/assets/8769619/23310888/b01b6572-fa79-11e6-8e3b-f7eea444187e.PNG)

**Comment by jessicagood** [comment]
@zmichels I moved this to its own issue since it's different from the symbol (special characters) problems. 

I added code to plot associated orientations. Added with commit d08fbd6b13084c59ad44ffc82899598ab5551f5c. And I fixed the problems with lineations using the default point symbol (a dot) instead of a line with an arrow. That was fixed with commit 651b6d53cfa9249a45e60bb6824d8ab21ff2975b.

I didn't officially release a new version yet but if you download the app again it should be fixed. Please let me know here if it's working properly now. Thanks.

**Comment by zmichels** [comment]
Great, thank you!
I just checked now and it looks good!


On Feb 24, 2017, at 3:41 PM, Jessica Good <notifications@github.com<mailto:notifications@github.com>> wrote:


@zmichels<https://github.com/zmichels> I moved this to its own issue since it's different from the symbol (special characters) problems.

I added code to plot associated orientations. Added with commit d08fbd6<https://github.com/StraboSpot/strabo-mobile/commit/d08fbd6b13084c59ad44ffc82899598ab5551f5c>. And I fixed the problems with lineations using the default point symbol (a dot) instead of a line with an arrow. That was fixed with commit 651b6d5<https://github.com/StraboSpot/strabo-mobile/commit/651b6d53cfa9249a45e60bb6824d8ab21ff2975b>.

I didn't officially release a new version yet but if you download the app again it should be fixed. Please let me know here if it's working properly now. Thanks.
