### ISSUE TITLE
Appearance of drop down menus

### ISSUE THREAD

**Issue by rtwilliamsgeo** [StraboSpot/strabo-mobile#359]
Basil requests that we change the appearance of drop down menus if possible. Currently, the down arrow is small and on the right-hand side. Ideally, it would be larger and on the left hand side.

**Comment by jessicagood** [comment]
The convention for drop-down menus is that the arrow is on the right. The text fills in on the left side once it's been selected. One doesn't need to even click on the arrow anyway, they only need to click in the blank space and the drop-down will open.

I recommend against this change. Anyone else have comments on this?

**Comment by rtwilliamsgeo** [comment]
This was really Basil's baby (he was weirdly adamant about it). I actually
agree with you. I'll try to talk to him about it Monday.

R

**Comment by panamint55** [comment]
We made a change with a light gray background.  This may make it clearer that the user can hit anywhere under the text or triangle and get the drop down.  We will see how this works.

**Comment by panamint55** [comment]
I think this changes should solve the issue.  Allen Glazner had the same comment.  We will need to make sure this is in FAQ and in the help.  We need to tell Carson about this.  Randy should talk with Basil and update him on this.  I will check with Allen.

**Comment by jessicagood** [comment]
This is available in release 0.18.8

**Comment by jessicagood** [comment]
Since this light gray background was not working for @btikoff the suggestion was made to change the background to yellow. How about the following instead? Adding the word '-----Select-----' and moving the drop-down arrow so it's not so far to the right? 

In the screenshot below I was also experimenting with putting any informational text about a field in a pop-up you get to by hitting the blue 'i' instead of having the text right after the field label. This allows for more fields on a screen and allows us to have a more complex/longer description of a field if necessary. 

Please let me know what you think before I push any changes. @rtwilliamsgeo @panamint55 @btikoff 

![image](https://user-images.githubusercontent.com/1493985/26961237-1f886986-4c92-11e7-9f51-5254b3c3c0bc.png)

**Comment by btikoff** [comment]
Ok, this is getting somewhere.  I like it - a lot.  It would be even better if it said Select (like it does now) AND also has color (as per Jason's suggestion).  The grey was an improvement but, it would be even better if there was a bright color.  I am 100% into Chartreuse for this field, partly because I think it would be effective, Doug might hate it, and we'd get to say chartreuse all the time.

**Comment by JEAndrew** [comment]
I like the blue (i) for the detail info. I don't really like the color chartreuse, it's way too 1960s. We could have a data input field look more like the current label and strike field where gray text tells the user about and where to input

**Comment by btikoff** [comment]
I like the blue info as well - that is a great addition.
As far as chartreuse, I don't really care except for one thing:  **What is visible in the field in full sunlight.**  The grey does not work even in drizzly Ireland.  I can't do this today because I'm in Seattle (no sun in sight), but just go out with an iPad in the sun and look at a color wheel and see what works.  Actually, I get to Boise tonight, so maybe I'll try it then.
They say that orange is the new black.  In fact, blaze orange is timeless (as far as hunters are concerned).
Given a choice, however, I am totally into chartreuse.  I bet it just shows up best.

**Comment by egbunse** [comment]
I really like the "Select" addition with the arrows moved up and think that solves the problem. I'm concerned that if we also make it a color people will think they are required to fill out that information and it will distract from the other fields. "Select" is attention-grabbing, but does not overpower the rest of the input choices.

**Comment by jessicagood** [comment]
I was trying to get away from having to use a color (chartreuse or any other color) because it won't look good and like @egbunse says will make users think they have to enter data there. (The green or red line under a field is supposed to indicate that now.) The other problem with coloring the field input line is then what about the label or any other text in the app? If it has to be chartreuse in order to be able to read the text then where do we stop in terms of making other text/background colors chartreuse? Do we make the whole app chartreuse?

Are there screen filters or some other way we can better deal with sunlight issues?

**Comment by panamint55** [comment]
I agree with Jessica.  The 20 or so students had no issues with this over the last week.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by zmichels** [comment]
I agree with Jessica and Doug.

On Jun 9, 2017, at 9:58 PM, panamint55 <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree with Jessica. The 20 or so students had no issues with this over the last week.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS 66045
785-864-7711
785-864-7789 (fax)
***********************************************

**Comment by jessicagood** [comment]
With commit 27b275201fcd4ece8aaf7c67895af01b7aa8f546. I added text to the default view of a drop-down menu which says what you are selecting. See below. I think this should make it more obvious that you don't only have to click on the tiny arrow.

![image](https://user-images.githubusercontent.com/1493985/27896415-c334ef4a-61ce-11e7-89bc-bac260f674ea.png)
