### ISSUE TITLE
MOBILE PRIORITY: Spot type changing

### ISSUE THREAD

**Issue by rtwilliamsgeo** [StraboSpot/strabo-mobile#360]
When adding a line or a polygon spot to the map, hitting go on the iOS keyboard changes the spot type back to a point. This error is reproducible, so give me a call if you want to see it in action.

**Comment by jessicagood** [comment]
Fixed with commit c585141.

The click action for the 'Set To My Location' button was being called when Go or Enter on the keyboard (iOS/Android/web) was pressed because the default action for buttons inside a form is `type="submit"`. Submit actions are run on keyboard Go/Enter presses.

I moved the tags for the form so none of the buttons were inside the form and this fixed the problem.
