### ISSUE TITLE
MOBILE PRIORITY: Relationship Display

### ISSUE THREAD

**Issue by rtwilliamsgeo** [StraboSpot/strabo-mobile#362]
The way saved relationships are displayed is somewhat clunky. Specifically, any one relationship takes up a lot of screen space due to being displayed on multiple lines. This could be troublesome for spots containing many relationships. Can we change it to be on one line? Something akin to:

measurement A _**Cross Cuts**_ measurement B

**Comment by jessicagood** [comment]
@rtwilliamsgeo I agree it does take up a lot of space but I don't think it can be as simplified as you're suggesting given the complexity of relationships. The way it is displayed now it is clearly indicated what is being included in which side of the relationship (Spots, Features and/or Tags). The user also can click on each Spot, Feature or Tag to get to more information about that item. 

I did however condense the information in such a way that on screens the size of a landscape phone or larger you have 3 columns instead of having everything stacked. I'm going to mark this issue closed (with commit 8160a32) but feel free to reopen if there is another way we can preserve the complexity of relationships but make the view simpler while still allowing the use to get more information about each item.
