### ISSUE TITLE
Symbology - overturned bedding

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#374]
From @btikoff: "Map symbology – there is no overturned bedding symbol.  It plots a “typical” strike and dip mark."

@JEAndrew Do you have the png for this that you could send me?

**Comment by JEAndrew** [comment]
![overturned](https://user-images.githubusercontent.com/11632667/27801479-df68ff90-5fe3-11e7-9712-139ea0eb86bd.png)

**Comment by JEAndrew** [comment]
Will this work? Let me know I can easily change the size and format. Sorry it took so long

**Comment by jessicagood** [comment]
@JEAndrew Do you want this vertical in it's default position (before rotation), like the others you sent me? Those were 167x667 and didn't have a white background.

**Comment by jessicagood** [comment]
@JEAndrew Still waiting on this when you get a chance.

**Comment by JEAndrew** [comment]
I am too remember putting a symbol into github a few weeks ago



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by zmichels** [comment]
yeah, that happened a while ago. this was it.

[cid:C2739CFC-8C5A-4B09-ADEF-9DBB66A413C1@umn.edu]

On Jul 13, 2017, at 8:34 AM, JEAndrew <notifications@github.com<mailto:notifications@github.com>> wrote:

I am too remember putting a symbol into github a few weeks ago



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by jessicagood** [comment]
Did you see my question after your comment about the initial orientation of
the symbol so when I apply the rotation in the same way as all the other
symbols we rotate it correctly? All the other symbols you sent me were
vertical and this one is horizontal. I'm assuming we should have this
symbol vertical as well but wanted to double check. And if you have a
larger copy, without a white background, like the others you sent, that
would be helpful. Otherwise I can make one.

On Jul 13, 2017 6:34 AM, "JEAndrew" <notifications@github.com> wrote:

I am too remember putting a symbol into github a few weeks ago



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by zmichels** [comment]
You are absolutely right, Jessica. The image should be rotated to match the others, so that when it is rotted as a symbol it communicates the proper information. I forget exactly how the unrotated other ones look, but the key attributes are the long line should match with other strike-dip symbols, and the “tail” stick off the long line should also match.


On Jul 13, 2017, at 9:34 AM, Jessica Good <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you see my question after your comment about the initial orientation of
the symbol so when I apply the rotation in the same way as all the other
symbols we rotate it correctly? All the other symbols you sent me were
vertical and this one is horizontal. I'm assuming we should have this
symbol vertical as well but wanted to double check. And if you have a
larger copy, without a white background, like the others you sent, that
would be helpful. Otherwise I can make one.

On Jul 13, 2017 6:34 AM, "JEAndrew" <notifications@github.com<mailto:notifications@github.com>> wrote:

I am too remember putting a symbol into github a few weeks ago



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by zmichels** [comment]
You are absolutely right, Jessica. The image should be rotated to match the others, so that when it is rotted as a symbol it communicates the proper information. I forget exactly how the unrotated other ones look, but the key attributes are the long line should match with other strike-dip symbols, and the “tail” stick off the long line should also match.

**Comment by jessicagood** [comment]
So like this before rotation?

![bedding_overturned](https://user-images.githubusercontent.com/1493985/28183448-5782175e-67c4-11e7-9c6f-2cc394969f37.png)

As we have it now for bedding:
dip = 0 we use the horizontal symbol
0 < dip < 90 inclined symbol
dip = 90 vertical symbol

How does overturned fit it in? Is the dip not relevant then and we need to look at the facing field instead?

**Comment by zmichels** [comment]
looks right.  And yes, the key is that the geologist thinks (or has evidence) that the (current) upward facing direction in the layering that defines the plane is not the original upward facing direction.


On Jul 13, 2017, at 2:24 PM, Jessica Good <notifications@github.com<mailto:notifications@github.com>> wrote:


So like this before rotation?

[bedding_overturned]<https://user-images.githubusercontent.com/1493985/28183448-5782175e-67c4-11e7-9c6f-2cc394969f37.png>

As we have it now for bedding:
dip = 0 we use the horizontal symbol
0 < dip < 90 inclined symbol
dip = 90 vertical symbol

How does overturned fit it in? Is the dip not relevant then and we need to look at the facing field instead?

**Comment by jessicagood** [comment]
Added with commit c06bf51.

I pulled the change into the PhoneGap Build test app. No new version number. Could you check it out and report back here if it's right? Thanks
