### ISSUE TITLE
Geologic map tiles.

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#47]
Can we integrate tiles like those available in the iOS app "Mancos"? Lots of geologists have told me that this is one of their favorite field apps for seeing geology context around them (or places they are going). IDK if this is worth a bunch of effort. I guess that's what I'm wondering... How much effort would something like that require?

**Comment by ginxwar** [comment]
We would need to know who the map provider is.  I dont know much about "Mancos" but from their website, it looks like they're using http://earth-base.org/ as their source data.  Going to http://earth-base.org (http://earth-base.org/macromap) reveals that they could be using Google Physical (aka MapTypeId.TERRAIN).

Can you confirm that the look/feel of the map tiles shown in "Mancos" is similar to http://earth-base.org/macromap ?

**Comment by zmichels** [comment]
Although I seem to be unable to view the same data at http://earth-base.org/macromap at the moment on my mobile as I could in the Mancos app, I agree that descriptions of the Mancos app seem to indicate the geologic data comes from earth-base.org. These would be the geologic maps (overlain on terrain or whatever other base tile imagery). The description also mentions paleodb.org for fossil info.

**Comment by ginxwar** [comment]
This may be difficult.  See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ol3-dev/ZV8LB-F5904/x1sspizm3xMJ

Short version is that Google maps only allows developers to access map tiles through the Google Maps API.  Using OL3 would be sketchy because if Google makes a change, it will break OL3 immediately.

There is a proof of work here at http://bl.ocks.org/elemoine/e82c7dd4b1d0ef45a9a4.  But even this page expresses that this code should not be used in production.

**Comment by zmichels** [comment]
Ok. Makes sense. Don't sweat it, and  thanks for looking into it.
