### ISSUE TITLE
Tab vs. Page

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/strabo-mobile#476]
I have gone thru the help document to change tab to page.  We need to do this in the app as well.  For example, on the preferences page it is called "tab control" and this should be changed.

I hope this is easy.  It will make our lives easier once done.

Doug

**Comment by jessicagood** [comment]
Does the StraboSpot website have the latest documentation? Looks like there are still some uses of "tab" in help documentation @NathanNovak downloaded today.

From the perspective of what the users sees this is easy to change. If I want to maintain consistency between what the user sees and the code itself then it is a much bigger task since I use the word "tab" in 158 different parts of the code. Find and replace will get me part of the way.

I always try to maintain consistency so ideally I'd like to change this in the code but I'm not sure if it's really worth our time. Either way we can definitely change what the user sees.

**Comment by panamint55** [comment]
I have prepared a new version.  I will send that out this afternoon.

Doug


***********************************************
J. Douglas Walker
Isotope Geochemistry Laboratories
Nichols Hall
2335 Irving Hill Drive
Lawrence, KS  66045
***********************************************

**Comment by jessicagood** [comment]
We have two "pages" for some things now. For example, we have the Spot Tags page and the Project Tags page. Likewise with Relationships, Images and Samples. So we're just going to have be careful to differentiate whether we're talking about a page at Spot level or at the Project level.

**Comment by NathanNovak** [comment]
fixed with commit dc894ec827f4104cb378ea24da86711236dc3dbc
