### ISSUE TITLE
Form generation/management

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#50]
Check out
- [XForms](http://www.w3.org/MarkUp/Forms/2003/xforms-for-html-authors#ASimpleSearchForm)
- [XLSForms](http://xlsform.org)
- [Kobo Toolbox](http://www.kobotoolbox.org)

**Comment by jessica-azgs** [comment]
@zmichels Can you follow this model for the creation of the forms? [XLSForms](http://xlsform.org)

This will be easier for @ginxwar and I to follow as we manually code the forms and down the road should allow us to generate the forms automatically. An XLSForm can be converted into an XForm.

Each content model should be its own form. The sooner you are able to get the XLSForms back to us, with the required fields, types, constraints, etc clearly laid out, the sooner we can code them into the app.

**Comment by ginxwar** [comment]
I spent some time tonight and played around with xlsforms and downloaded their pizza questionaire example.  Then I downloaded the python transformer that converted the xlsforms data into XForms, which is just XML under the covers.  Finally I tried loading the XForm file into Kobo Toolbox but realized that they didn't 100% support XForms with regard to "skip logic."  The specific error is: "Exporting skip logic in XLSForms is not currently supported."

So I tried a *different* brand new file with a **single** question and imported that.  Kobo responds with: "XForm imports are not fully supported. Please check the correctness of the resulting survey."

The workflow was basically: xlsforms (excel) -> XForm (xml) -> Kobo

It's not perfect in the manner that we could automate this -- but definitely doable if human eyeballs can verify the import in the Kobo interface.

*But* I'm still trying to figure out how we could use this in our angular project...  @jessica-azgs, maybe I'm missing the big picture?  I think I just need a nudge.

**Comment by jessica-azgs** [comment]
We need a standardized way to describe the fields and choices for the
different forms (different content models) that the app will use when a
user is creating different types of spots. If the best way to describe the
form content is an xform (xml) we also need some way for the app to
construct the form given the xml so the forms do not have to be hard-coded
(like it is now). Since there are a bunch of different applications like
Kobo that use xlsForms/xforms there just be some process to convert the xml
to an HTML form. But maybe there are other ways besides xforms as well -
xforms seems promising but I hadn't been able to look into it too much yet.

**Comment by ginxwar** [comment]
Makes sense.  But it appears that XForms is mostly dead now as most browsers dont recognize it unless you transform it.  It seems the way most folks use XForms now is uploading them to 3rd party services like Kobo, Enketo, or Orbeon that is hosted on their servers.

If I understand correctly, what we want is something that can transform XForm into their equivalent HTML forms, which likely is just a XSLT transformation since XForm is just a XML document.  The closest I've found is: http://xslt-dev.enketo.org but it does not fully support XForm logic, as described here https://github.com/enketo/enketo-xslt-transformer-php.  This is probably a dealbreaker if the form content models are complex enough such that form responses are dependent on previous form responses, e.g. the pizza questionnaire example from xlsforms.

Some ideas:
     
1) If there are lots and lots of forms to generate, we could run this: https://github.com/enketo/enketo-core, and then somehow scrap the generated html from the server and apply a css transformation to suit our needs
2) I'm also wondering if we could scrap https://www.enketo.org/ after we upload a XForm document to them through one of their plans.
3) write our own XSLT transformation, taking in a XForm document and output a html document that uses ionic framework tags

**Comment by zmichels** [comment]
Well... I am sending what I have. It is not in the XLForms standard, but I hope it is more easy to follow. I tried to normalize possible content into separate sheets in an XLS file. I am sure it is incomplete... and so far is just focused on the basics for capturing line and plane information. I can't seem to paste here, so I will email to you now.

**Comment by jessica-azgs** [comment]
Looks like maybe the XSLT transformation is the way to go. That might need to be generated server side and downloaded into the app?

**Comment by ginxwar** [comment]
I spent more time on xforms today.  Here's what I know:

In a conversation with Jessica, she says that ideally there should be a workflow that automatically converts the XlsForms that researchers create into web forms that we could easily bring into our mobile app.  This workflow is important and goal worthy because future web forms could be automated directly from XlsForms into web forms and may have additional usage beyond strabo-mobile.

Since our mobile app is html with ionic flavors, we would need to develop a workflow that is something like this:

##### Xlsforms --> XForms --> HTML + Ionic

The underlying document for the above is really just:

##### Excel --> XML --> HTML (with Ionic markup)

Going from XlsForms to XForms is easy as there is already a project that will do this with no work at all (https://github.com/SEL-Columbia/pyxform)

But going from XForms to HTML is not as straightforward.  It seems that there's a lot of 3rd party services that host and collect form data but one thing is common -- they all use Enketo as their engine for translating XForms to HTML.  To do this, we need these 2 projects:

* Enketo-xslt (https://github.com/enketo/enketo-xslt/blob/master/openrosa2html5form.xsl) provides the xslt transformation from raw Xforms to HTML.  
* Enketo-core (https://github.com/enketo/enketo-core) provides the mechanism to build your own "Enketo" app, which is what you would see when you publish your form on services like kobotoolbox, ona, formhub, etc.

Enketo-xslt essentially converts from:

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Pizza</h:title>
    <model>
      <instance>
        <Pizza id="Pizza">
          <Do_you_like_pizza/>
          <Pizza_Toppings/>
          <Why_not/>
          <meta>
            <instanceID/>
          </meta>
        </Pizza>
      </instance>
      <bind nodeset="/Pizza/Do_you_like_pizza" required="true()" type="select1"/>
      <bind nodeset="/Pizza/Pizza_Toppings" relevant=" /Pizza/Do_you_like_pizza  = 'yes'" required="true()" type="select"/>
      <bind nodeset="/Pizza/Why_not" relevant=" /Pizza/Do_you_like_pizza  = 'no'" required="true()" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/Pizza/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <select1 ref="/Pizza/Do_you_like_pizza">
      <label>Do you like pizza?</label>
      <item>
        <label>Yes</label>
        <value>yes</value>
      </item>
      <item>
        <label>No</label>
        <value>no</value>
      </item>
    </select1>
    <select ref="/Pizza/Pizza_Toppings">
      <label>Pizza Toppings</label>
      <item>
        <label>Muchroom</label>
        <value>muchroom</value>
      </item>
      <item>
        <label>Pepperoni</label>
        <value>pepperoni</value>
      </item>
      <item>
        <label>Sausage</label>
        <value>sausage</value>
      </item>
      <item>
        <label>Bell Peppers</label>
        <value>bell_peppers</value>
      </item>
    </select>
    <input ref="/Pizza/Why_not">
      <label>Why not?</label>
    </input>
  </h:body>
</h:html>
```


to:
````html
<form autocomplete="off" novalidate="novalidate" class="or clearfix" id="Pizza">
  <!--This form was created by transforming a OpenRosa-flavored (X)Form using an XSLT sheet created by Enketo LLC.-->
  <section class="form-logo"> </section>
  <h3 id="form-title">Pizza</h3>


  <fieldset class="question ">
    <fieldset>
      <legend>
        <span lang="" class="question-label active">Do you like pizza?</span>
        <span class="required">*</span>
      </legend>
      <div class="option-wrapper">
        <label class="">
          <input type="radio" name="/Pizza/Do_you_like_pizza" data-name="/Pizza/Do_you_like_pizza" value="yes" required="required" data-type-xml="select1" />
          <span lang="" class="option-label active">Yes</span>
        </label>
        <label class="">
          <input type="radio" name="/Pizza/Do_you_like_pizza" data-name="/Pizza/Do_you_like_pizza" value="no" required="required" data-type-xml="select1" />
          <span lang="" class="option-label active">No</span>
        </label>
      </div>
    </fieldset>
  </fieldset>
  <fieldset class="question or-branch pre-init ">
    <fieldset>
      <legend>
        <span lang="" class="question-label active">Pizza Toppings</span>
        <span class="required">*</span>
      </legend>
      <div class="option-wrapper">
        <label class="">
          <input type="checkbox" name="/Pizza/Pizza_Toppings" value="muchroom" required="required" data-relevant=" /Pizza/Do_you_like_pizza  = 'yes'" data-type-xml="select" />
          <span lang="" class="option-label active">Muchroom</span>
        </label>
        <label class="">
          <input type="checkbox" name="/Pizza/Pizza_Toppings" value="pepperoni" required="required" data-relevant=" /Pizza/Do_you_like_pizza  = 'yes'" data-type-xml="select" />
          <span lang="" class="option-label active">Pepperoni</span>
        </label>
        <label class="">
          <input type="checkbox" name="/Pizza/Pizza_Toppings" value="sausage" required="required" data-relevant=" /Pizza/Do_you_like_pizza  = 'yes'" data-type-xml="select" />
          <span lang="" class="option-label active">Sausage</span>
        </label>
        <label class="">
          <input type="checkbox" name="/Pizza/Pizza_Toppings" value="bell_peppers" required="required" data-relevant=" /Pizza/Do_you_like_pizza  = 'yes'" data-type-xml="select" />
          <span lang="" class="option-label active">Bell Peppers</span>
        </label>
      </div>
    </fieldset>
  </fieldset>
  <label class="question or-branch pre-init non-select ">
    <span lang="" class="question-label active">Why not?</span>
    <span class="required">*</span>
    <input type="text" name="/Pizza/Why_not" required="required" data-relevant=" /Pizza/Do_you_like_pizza  = 'no'" data-type-xml="string" />
  </label>

  <fieldset id="or-calculated-items" style="display:none;">
    <label class="calculation non-select ">
      <input type="hidden" name="/Pizza/meta/instanceID" data-calculate="concat('uuid:', uuid())" data-type-xml="string" />
    </label>
  </fieldset>
</form>
```

Great!  It looks like HTML so it sounds like we have a winner.  Err, not quite.  Here's where things get tricky.  The xslt transformation does everything right and can convert from XForms into HTML.  In the example above, the second question of "Pizza Toppings" is dependent on the user answering the question "Do you like pizza" and responding "Yes."  Responding "No" will skip to the third question of "Why not?"

All of the javascript goodness of validation, logic flow, constraints, and other conditions that XlsForms allow are done in the enketo-core project.  I've checked in a new branch (enketo-core, 3e6de80c314810639ff66367b8254e83cfa9db5a) that incorporates all of the enketo-core requirements but I still need to figure out how to incorporate this with angular.  Also, enketo-core heavily uses jquery for DOM validation and logic -- not sure how compatible we could make this as part of our app.  This branch is totally broken and is used to determine how to get the framework going with angular.

I'm inclined to think this should be separate project outside of strabo-mobile and something we may want to postpone and spin off into its own thing.

Thoughts?
