### ISSUE TITLE
Don't lose DB login information when switching pages

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#51]

**Comment by ginxwar** [comment]
Created a LoginFactory to support this.  Outstanding issue remains:

1) cannot test actual login against strabo server due to errors.  See https://github.com/StraboSpot/strabo-server/issues/12
2) Login information should be stored in an offline database for persistence

**Comment by ginxwar** [comment]
See 3721388e4d9674e1e77b65dc41d57feeea568ddf.
Not sure about login information should be stored in an offline database for persistence?

**Comment by jessica-azgs** [comment]
Yeah, the user shouldn't have to login every time they open the app. That will present some security issues no doubt but the whole login as it stands now isn't even secure.

**Comment by jasonash** [comment]
The question of login security has come up recently and I was just 
wondering what people's thoughts are on the issue. Should we try and get 
an SSL certificate? Should we otherwise obfuscate login information? I'm 
not sure how the AZ Survey handles this with other projects. I am 
willing to setup an SSL cert, but there is an obvious cost that needs to 
be discussed. Wildcard certificates are typically several hundred 
dollars a year, and we would have to decide who is willing to manage 
these moving forward.

**Comment by ginxwar** [comment]
login data now persists in offline database.  See 70fdee611d737861060d5cd002976f6445872398
