### ISSUE TITLE
Minerals in "Mineral Glossary" and "Full Mineral List" do not match up. 

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/strabo-mobile#584]
There are a number of minerals on the "Full Minerals List" in the Mineralogy tab that are not in the Mineral Glossary, and vice versa. Some of these make sense, as the "Full Minerals List" is not including sedimentary minerals, such as gypsum or halite. 

I can do the work to make the lists match by adding the missing minerals from each list to where they are missing. I am currently working on classifying the minerals. and getting the abbreviations.  Just wanted to alert you of the issue.

**Comment by hannahcunning** [comment]
[Mineral lists.docx](https://github.com/StraboSpot/strabo-mobile/files/3575619/Mineral.lists.docx)

**Comment by jessicagood** [comment]
@hannahcunning Ah, yes, started looking at this but then got headed down another rabbit hole. I copied the glossary from a minerals sections that Nathan had worked with Allen on last summer. That included sedimentary minerals apparently. Should the sedimentary minerals (and any other types of minerals) be included in the Pet Minerals/Mineralogy page? Up to you all.

**Comment by jessicagood** [comment]
@hannahcunning In case it helps, if you log into the main Strabo KoBo forms account (let me know if you need the pw) you'll see all the minerals from the old mineral section (that was never used except testing and I was asked to remove).  There are forms for for All and Most Common for Heavy Minerals, Igneous, Metamorphic and Sedimentary.

**Comment by hannahcunning** [comment]
I have the list and will begin editing the kobo forms to add the minerals and make changes. Other than the updated list of minerals, is there anything you need to update the Mineral glossary?

**Comment by jessicagood** [comment]
If you want to add any minerals to the glossary or take away minerals (because you don't want sedimentary minerals here or some other reason) I need to know which ones. And for add minerals I need all the info that the other minerals in the glossary have.

Just make sure you don't remove or change the names of any of the minerals that are coming from  Rock Unit. If you want minerals from Rock Unit copied over to Petrology they each a place to go.

**Comment by jessicagood** [comment]
Here is the data I'm using for the glossary if you want to add to it. The abbreviations should also be added to this. Note somehow it looks like melilite lost some info.

[MineralGlossary.xlsx](https://github.com/StraboSpot/strabo-mobile/files/3575893/MineralGlossary.xlsx)

**Comment by jessicagood** [comment]
@hannahcunning I edited the file above to include the abbreviations you had so if you've downloaded it make sure you download it again. I need the abbreviations in this file to start fixing some of the code but there is still missing info for the glossary.

**Comment by hannahcunning** [comment]
So do you mean that the minerals from the old Minerals section cannot be changed and must be on the new "Full Mineral List" and in the Mineral Glossary? There are several instances where this would not be appropriate, as I have outlined in the following document. 

I will work on adding the information to for the new minerals in the glossary. 

[Mineral conflicts.xlsx](https://github.com/StraboSpot/strabo-mobile/files/3576108/Mineral.conflicts.xlsx)

**Comment by jessicagood** [comment]
We have 4 places (I think) where there are minerals. Rock Unit, Pet Minerals, the Minerals Tag (Nathan did last summer and I'm deleting) and in Sed (??). The current glossary I pulled from the Minerals Tag. Anything in that came from Minerals Tag you can choose to include or not.

The thing we have to think about is what happens when someone selects a volcanic, plutonic or metamorphic mineral in the Rock Unit and that is copied over to Pet. Those minerals need to exist in Pet so they can be copied over. If someone selects 'chert' for example that doesn't matter since it's not a volcanic, plutonic or metamorphic mineral and it's only volcanic, plutonic or metamorphic minerals that are copied to Pet.

I can write code for a few exceptions if we need to, I just need to know which are the ones that won't copy to Pet.

**Comment by hannahcunning** [comment]
I am having trouble finding minerals anywhere except for in Sed, the Minerals tag, and the Pet Minerals. I don't see any minerals in Rock Unit (where you create a rock unit tag). If you are referring to something else I have overlooked then I will add those to the list.

**Comment by panamint55** [comment]
No, that is probably it.  My only point is that in both sed and ig it is still just minerals.

The minerals tag is going away.

Doug

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by jessicagood** [comment]
@hannahcunning I think I was mixing up rock type with mineral. Rock type is the field in Rock Unit that is copied over to Pet Mineralogy.

**Comment by hannahcunning** [comment]
Jessica, here is the updated Mineral glossary. I will let you know when I have the kobo forms updated.
[MineralGlossary_hannahupdates.xlsx](https://github.com/StraboSpot/strabo-mobile/files/3591120/MineralGlossary_hannahupdates.xlsx)

**Comment by hannahcunning** [comment]
Jessica, 
I have updated the kobo forms.

**Comment by jessicagood** [comment]
FYI, you have `Cr-diopside` under Mineral but not under one of the classes. Not sure if that's on purpose or not.

**Comment by jessicagood** [comment]
Same with `spodumene`.

**Comment by hannahcunning** [comment]
This is on purpose, according to the list I was given.

**Comment by jessicagood** [comment]
@hannahcunning Ok, this is in all in the code. Note I changed the names of the 3 forms we're using in KoBo forms to match the names of the subtabs in the app - Rock, Minerals and Reactions. A form for ternary is not needed and can be deleted, along with any other forms you want (except the first 3) so the list is cleaned up.
