### ISSUE TITLE
Petrology Pages (Names & Organization)

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-mobile#585]
@hannahcunning @aglazner @btikoff 

At the meeting someone suggested changing the name of the `Pet Basics` page to `Ig/Met`. Is that what you want? Should it be `Pet Ig/Met` to make it more similar to `Pet Minerals`?

Or do you want `Basics`, `Mineralogy`, `Reactions`, `Ternary` all under one `Petrology` page? To me this makes more sense but I'm not a geologist. **The data structure I'm using is modeled after the page structure so it's much better to get this organization settled earlier rather than later.** And the organization should take into account future additions you may want. Like if the petrology pages are just handling igneous and metamorphic where are sedimentary minerals going and heavy minerals? Are there going to be other petrology pages? Where will the `Fabrics` page you want go? Is that under `Petrology`?

**Comment by aglazner** [comment]
My druthers are a main tab that is either Pet or Ig/Met (Pet being as opposed to Sed, I think that’s clear enough to people), and the 4 tabs you mention below under that.

I think Doug needs to weigh in regarding the bold and later stuff below.

So my suggestion would be

Pet
Rock, Minerals, Reactions, Ternary

and then

Sed
[all the stuff they need]

I will be back in Gunnison tonight but then in Capitol Reef, etc., camping, without much access until about the 9th. I will have phone service, though, sometimes.

On Sep 4, 2019, at 11:41 AM, Jessica Good <notifications@github.com<mailto:notifications@github.com>> wrote:


@hannahcunning<https://github.com/hannahcunning> @aglazner<https://github.com/aglazner> @btikoff<https://github.com/btikoff>

At the meeting someone suggested changing the name of the Pet Basics page to Ig/Met. Is that what you want? Should it be Pet Ig/Met to make it more similar to Pet Minerals?

Or do you want Basics, Mineralogy, Reactions, Ternary all under one Petrology page? To me this makes more sense but I'm not a geologist. The data structure I'm using is modeled after the page structure so it's much better to get this organization settled earlier rather than later. And the organization should take into account future additions you may want. Like if the petrology pages are just handling igneous and metamorphic where are sedimentary minerals going and heavy minerals? Are there going to be other petrology pages? Where will the Fabrics page you want go? Is that under Petrology?

**Comment by panamint55** [comment]
The main concern here is whether Basics, Mineralogy, Reactions, Ternary will be widely applied to non-petrology spots.  For example, Orientation and Sample are separate tabs so that they are obvious for all spots.  For sedimentology, it is so specific and verbose that most of the descriptions are no general, and only apply to this.

I would say that IG-MET-PET would be good as a tab with the others under it.  My only concern, and I have not tried this or even really worked it through my head in the field, is how general mineralogy should be.  My first reaction is that mineralogy applies to all rocks and should be its own tag without qualifiers.  That said, the ways sed, ig, met, and general mappers use it is a bit different and a somewhat different workflow.

Regardless, the database itself should have only one instance of minerals and reactions and modal percents that is just general for rocks.  We can serve this up in different ways for different uses, but only one underlying value.

So, I would say IG-MET-PET with all the others under it fits with the motif we have set up for sed, which once you get use to it, it a fine workflow.

Doug

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by aglazner** [comment]
What he said, but I would suggest, now that I’ve read his comment, that Ternary is applicable to a lot of subfields, since it is used widely in classification in sed rocks, volcaniclastic rocks, etc. So maybe Ternary should be a first-level tab that people can turn on or off, rather than a sub-tab under Ig/Met. It would need to be able to access various data fields for its plots (duh).

Hannah, if you get this please explain @ stuff to me as I have studiously avoided using it until now but can’t tell from the To and Cc fields who is getting this.

On Sep 5, 2019, at 8:16 AM, panamint55 <notifications@github.com<mailto:notifications@github.com>> wrote:

The main concern here is whether Basics, Mineralogy, Reactions, Ternary will be widely applied to non-petrology spots. For example, Orientation and Sample are separate tabs so that they are obvious for all spots. For sedimentology, it is so specific and verbose that most of the descriptions are no general, and only apply to this.

I would say that IG-MET-PET would be good as a tab with the others under it. My only concern, and I have not tried this or even really worked it through my head in the field, is how general mineralogy should be. My first reaction is that mineralogy applies to all rocks and should be its own tag without qualifiers. That said, the ways sed, ig, met, and general mappers use it is a bit different and a somewhat different workflow.

Regardless, the database itself should have only one instance of minerals and reactions and modal percents that is just general for rocks. We can serve this up in different ways for different uses, but only one underlying value.

So, I would say IG-MET-PET with all the others under it fits with the motif we have set up for sed, which once you get use to it, it a fine workflow.

Doug

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by hannahcunning** [comment]
Alan, 
Since we all have been '@-ed' in this thread we are all getting notifications whenever someone replies. I have gotten email updates each time someone replies even though they don't '@' me in every reply.

**Comment by jessicagood** [comment]
A simpler name than IG/MET/PET would be better in my opinion but I can certainly make it IG/MET/PET (slashes look better than the dashes I think and take up less room).Then the following secondary level pages:

IG/MET/PET
    Pet Rock
    Minerals
    Reactions
    Ternary

Right now Ternary is only using fields from Pet Minerals -> Mineralogy so maybe we keep it under IG/MET/PET and move it when we start using data from fields on other pages? This page doesn't store any data so it's easier to move around.
   
We need to finalize this today if I'm to fix the app tomorrow and get out a version for testing for the field trip. Does @btikoff need to weigh in? I don't think he's looking at this.

@pantamint55 In terms of storing the data sed minerals are stored under sed and these would be stored under ig-met-pet. Storing them all together would mean changing sed forms. I can look into it.

**Comment by panamint55** [comment]
That is ugly, but not sure what is better.  Ideas?

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by aglazner** [comment]
I suggest Ig/Met with tabs for Rock, Minerals, Reactions, Ternary, except that I would still pull Ternary out into its own tab. “Pet” is not needed.

On Sep 9, 2019, at 8:10 AM, panamint55 <notifications@github.com<mailto:notifications@github.com>> wrote:

That is ugly, but not sure what is better. Ideas?

*****************************
J. Douglas Walker
Department of Geology
Ritchie Hall
1414 Naismith Dr., Room 254
Lawrence, KS 66045-3106
*****************************

**Comment by jessicagood** [comment]
Implemented in commit d422e1f93041ddee6a0822f295d5cbb74bf7e5c9.

@aglazner I left Ternary alone for now since it's only using data from Ig/Met but we can move it later.
