### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by aglazner** [StraboSpot/strabo-mobile#592]
**Is your feature request related to a problem? Please describe.**

I just drew a polygon around a large set of points that I wanted to distinguish on the map as “Stop 2 area”. I experimented with different types to find one with either no fill or a faint fill, to no avail. So I went to delete the polygon, but can’t do that without deleting all the spots inside! Now I’m stuck with the polygon.

**Describe the solution you'd like**

You should be able to just delete the polygon. A similar situation exists with spots; you can’t delete a spot if there are any images—but you should be able to.

**Describe alternatives you've considered**

Pills.

**Additional context**

**Comment by jessicagood** [comment]
Fixed with commit 2dc439c. I added a check to see if any of the "children" Spots are mapped on an image basemap or strat section. If so we don't want to let the user delete the Spot, if not, yes, you should be able to delete the Spot. This is updated in PhoneGap. No new version. I'll look at the images issue.

**Comment by jessicagood** [comment]
Also, if you draw a polygon and set the Surface Feature Type on the main Spot tab to 'Extent of Mapping' there is no fill.
