### ISSUE TITLE
Spots Detail Pane Not Behaving Correctly on Desktop Version

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#615]
On the desktop version, the spot details pane on the map view seems to be behaving incorrectly. When you click on a spot, the spot details are shown, but when you click off of the spot on a random point on the map, the typical "No Spot Selected" message appears at the top of the bar, but the spot details are not cleared.

Here is a screenshot
<img width="1458" alt="Screenshot 2020-05-01 11 52 57" src="https://user-images.githubusercontent.com/7904402/80823750-cab45480-8ba2-11ea-9c15-011481db0435.png">

**Comment by jessicagood** [comment]
Is this happening with every project. I can't recreate it in the dev environment or at https://strabospot.org/. It's especially weird because the lines that show "No Spot Selected" vs Spot info are mutually exclusive.

     <div ng-show='vm.clickedFeatureId === undefined'>
        No Spot Selected
     </div>
     <div ng-hide='vm.clickedFeatureId === undefined'>
        ...
https://github.com/StraboSpot/strabo-mobile/blob/ffab999e2d88a6fb859f2c32943f2c0e0ce47e71/www/app/maps/side-panel/side-panel.template.html#L2

**Comment by jasonash** [comment]
I just did some more testing and I am also unable to recreate the issue now. I'm wondering if it had something to do with repeatedly clearing my browser cache last week when debugging the desktop issue. I'll close for now.
