### ISSUE TITLE
Check out Mancos app

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#69]
http://www.appannie.com/apps/ios/app/mancos/

Is there any way to incorporate the geologic maps into our app like they do?

**Comment by ginxwar** [comment]
Mancos is using Google Physical as their map tile provider.  Initially, it looked like the reason OL3 can't use Google Physical is due to Google's TOS (https://developers.google.com/maps/terms) in section 10.2, but I think recent conversations are suggesting that the OL3 developers wont work on this because Google Maps changes their API too often that it becomes unsupportable.  See https://github.com/openlayers/ol3/issues/2205

OL3 has a proof of concept for a Google map here,  http://openlayers.org/en/v3.0.0/examples/google-map.html, but this implementation is using a wrapper.  This means that integrating this into the layerswitcher would be close to impossible without some major architectural rewrite.

Similarly, Leaflet's documentation also suggests that their APIs is just a wrapper/proxy against Google Maps JS engine.

I have to admit though, Google Physical maps are gorgeous.

**Comment by zmichels** [comment]
I have a probably ignorant question:
Are these same issues Kevin mentions valid for the geologic map data Mancos drapes on the imagery (I realize they are probably being served and tiled with the Google Physical maps, but I just want to check)? Our interest in making it "look like Mancos" was really to integrate the geologic maps being drawn without having to reinvent the wheel. Not concerned about the specific background and layers switchers.
So... short version, can we get at the geologic map data that Mancos use, so as not to have to make our own?

**Comment by ginxwar** [comment]
Hi @zmichels, 

I dont have the Mancos app installed, but if you have Mancos, could you take a screenshot of the map you would like to have?  Maybe that can give me a better idea of which map/overlay you're after.  I've based my discovery of the Mancos base layer from the Mancos app site which says:

>   "Mancos brings the geology of the United States to your iPhone. Tap the map, search by name, or use GPS to instantly locate yourself, show state-level geological maps, the geological formation and the regional stratigraphic column, all supplied by the servers at **earth-base.org**. Also view any fossil collections from your region, supplied by ..."

The earth-base.org has a couple of interesting maps.  One of them (http://earth-base.org/geomaps) shows Google Physical as the base layer with the option of selecting 4 different overlays:

![image](https://cloud.githubusercontent.com/assets/1930629/6162473/a12bb03e-b238-11e4-92cc-2f33111c0b14.png)

Is it possible you're referring to the overlays?

**Comment by zmichels** [comment]
Yes... The Geologic maps/overlays are what I'm talking about. I have not used Mancos much, but I have heard other geologists say that they like the way the maps look... They don't seem to car about the specific base layers. I tried to insert a screenshot in my last email response, but I think I need to do it directly thru github. I'll do that when I get into the office in a bit.

**Comment by zmichels** [comment]
![](http://i.imgur.com/6LkfQT7.jpg)

**Comment by ginxwar** [comment]
Ah, then this might work.  I've been fiddling with this for a couple of hours now but I'm having no luck.  The tile server at earth-base.org uses WMS with a EPSG projection of 900913 (which in theory is equivalent to EPSG:3857) but I couldn't get it to work.

The plan should be to add the EPSG:900913 tiles from earth-base.org and create its own map layer.

I'll continue to take a look at this later.

**Comment by ginxwar** [comment]
After spending quite some time looking at this, I'm lead to believe there's something about the configuration of the map server that's causing issues and I wrote an email to the PI running the earth-base.org service.

The issue appears to be a strict extent type of the lower X bound when trying to retrieve map tiles from earth-base.org.  The WMS service for the following 4 service providers all work without issue:
```
// URL: "http://watzmann.geog.uni-heidelberg.de/cached/osm"
// LAYERS: "osm_auto:all"
// Projection: EPSG:3857 or EPSG:900913

// URL: "http://irs.gis-lab.info"
// LAYERS: "landsat"
// Projection: EPSG:3857 or EPSG:900913

// URL: "http://sedac.ciesin.columbia.edu/geoserver/wms"
// LAYERS: "gpw-v3:gpw-v3-population-density_2000"
// Projection: EPSG:3857 or EPSG:900913

// URL: "http://gis1.usgs.gov/arcgis/services/gap/PADUS_Owner/MapServer/WMSServer"
// LAYERS: "0"
// Projection: EPSG:3857 (only!)
```
However, http://earth-base.org/tilecache/tilecache.cgi, doesn't like the lower X bound generated by OL3.  Here's a trace:
```
curl "http://earth-base.org/tilecache/tilecache.cgi?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=gmna_units_time&WIDTH=256&HEIGHT=256&SRS=EPSG%3A3857&STYLES=&BBOX=-10018754.171394622,5009377.085697312,-7514065.628545966,7514065.628545968"

An error occurred: Current x value -10018754.171395 is too far from tile corner x -12523442.712800
```
But the following server response works:
```
curl "http://earth-base.org/tilecache/tilecache.cgi?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=gmna_units_time&WIDTH=256&HEIGHT=256&SRS=EPSG%3A3857&STYLES=&BBOX=-10018753.83,5009377.425,-7514065.2875,7514065.9675"
```
You can see that the lower X bound is a bit off when comparing the two requests.  I then changed the lower X bound from -10018754.171394622 to -10018753.83 and that does indeed work, so I'm thinking the calculation is quite strict on the TileCache server.  All 4 WMS services noted above work with either example.

I've asked if the PI at earth-base.org could point me to a technical contact so that they could relax the extent type to be more loose.

**Comment by ginxwar** [comment]
Bingo!  I got a response from the technical coordinator at earth-base.org.  Pasting relevant details here:
> We are in the process of deprecating services from earth-base.org. We have replaced the WMS server with standard z/x/y tiles, which can be found at http://macrostrat.org/tiles/<tileset>/<z>/<x>/<y>.png

> Right now we have GMNA and GMUS tilesets, and you can find basic metadata about each at http://macrostrat.org/tiles/gmna/metadata.json and http://macrostrat.org/tiles/gmus/metadata.json. 

> We also have a tileset 'geologic' that is a combination of GMNA and GMUS, which is what we use in this demo web application - http://macrostrat.org/gmna

> For now, these tiles should be consistent and not change in any meaningful way, but we are in the process of increasing the temporal resolution of GMUS, so styling may change in the future. We're not quite ready to commit to stable versions yet, but you can be assured that these are relatively static. 

Added an overlay layer to the map.  By default, this visibility is set to false.  Enabling it will enable the overlay.  See e6c267da9a178ace9fb232bdc1d0c989f45fec23.

We may want to check-in with the macrostrat folks every now and then to see if they've updated their tiles with new information.  I've also asked for their terms of service just in case too.

**Comment by jessica-azgs** [comment]
This looks awesome Kevin. Great work.

**Comment by zmichels** [comment]
Yeah, looks great. Thanks for all the effort to get it figured out!
