### ISSUE TITLE
Cache Geologic Maps Overlay

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#75]
If the geologic maps overlay is turned on when the cache map button is pressed, the overlay tiles should be cached as well.

**Comment by ginxwar** [comment]
See 7df6930ce46b9f448f09e59514349a8a123fe985.  I spent quite a bit of time on this (week+) banging my head because I was initially going down the route where each online map layer would dynamically switch sources using ```ol.layer.Tile.setSource()```.  I found out the hard way that the ```setSource()``` method doesn't dispatch the source change properly.  The ```setSource()``` was never meant to be used in this manner where you would swap out sources AFTER the layer has been defined.

There's an open issue about this (https://github.com/openlayers/ol3/issues/2683) but the current recommended way is to just create a whole new layer with the custom source baked directly into the layer properties.

What I did for this issue:

* macrostrat-geologic tiles are now automatically archived during any map download event
  * added macrostrat-geologic as a map provider
* refactored map tiles (map.js) so that they're more maintainable 
* made ```tileLoadFunction``` more generic
* made the map tiles/overlays more clear to the user whether online or offline mode
* watching ```$scope.airplaneMode``` is now better defined as to what layers are being swapped out

Note that macrostrat tiles are only available for zoom 4-12 at the moment so attempting to archive inner zooms beyond zoom 12 for macrostrat would result in a 0 byte file.  The macrostrat folks say this may change later when they increase the resolution of their map tile service.
