### ISSUE TITLE
Update Related Spots Ids

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#82]
When a spot X is uploaded to the database an `id` is assigned by the database. All spots that have spot X in their related_spots list need to update the id used in the related_spots list too.

**Comment by smrazgs** [comment]
@jasonash @jessica-azgs please see discussion on identifier handling at https://github.com/StraboSpot/strabo-mobile/wiki/Identifier-handling.  I think we need to be forward thinking if possible to a situation with multiple users, and links between spots in different projects. If projects are specific to individual users, we need a different name for that kind of thing, and reserve 'project' for something that corresponds more closely to a research project that may involve multiple users sharing data.

**Comment by jasonash** [comment]
@smrazgs Steve, thanks so much for the detailed explanation. I think this should definitely work. One thing I'm not so sure about is the "holding tank" idea. Shouldn't the database just update on receiving a valid unique id?

Whatever the case, I will begin rewriting the API to account for the new user/project identifier handling.

One change we need to make to the backend is to leverage Neo4J's complex relationship handling. To date, these relationships have been reported to the database as a "links" attribute in the spot properties. I will work with Jessica to get details on the definition of these "links" attributes so that the correct relationships can be made in Neo4J.
